export type ReportStatus = "published" | "draft";
export type ResearchCategory = "AI公司" | "互联网公司";

export type ReportCatalogEntry = {
  id: string;
  companyId: string;
  companyName: string;
  companyNameEn: string;
  ticker: string;
  category: ResearchCategory;
  iconUrl: string;
  fiscalYear: number;
  quarter: "Q1" | "Q2" | "Q3" | "Q4" | "FY";
  periodLabel: string;
  publishedAt: string;
  endpoint: string;
  status: ReportStatus;
};

const DEFAULT_ENDPOINT =
  "https://82.157.208.201/financial-data/meituan-2026-q1.json";

/**
 * Add future companies and quarters here. The interface derives both selectors
 * and the research-library navigation from this single registry.
 */
export const REPORT_CATALOG: ReportCatalogEntry[] = [
  {
    id: "meta-fy2025",
    companyId: "meta",
    companyName: "Meta Platforms",
    companyNameEn: "Meta Platforms, Inc.",
    ticker: "META",
    category: "AI公司",
    iconUrl: "/company-icons/meta.svg",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/meta-fy2025.json",
    status: "published",
  },
  {
    id: "alphabet-fy2025",
    companyId: "alphabet",
    companyName: "谷歌母公司 Alphabet",
    companyNameEn: "Alphabet Inc.",
    ticker: "GOOGL",
    category: "AI公司",
    iconUrl: "/company-icons/google.svg",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/googl-fy2025.json",
    status: "published",
  },
  {
    id: "tripcom-fy2025",
    companyId: "tripcom",
    companyName: "携程集团",
    companyNameEn: "Trip.com Group",
    ticker: "9961.HK",
    category: "互联网公司",
    iconUrl: "/company-icons/tripcom.svg",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/9961-hk-fy2025.json",
    status: "published",
  },
  {
    id: "pdd-fy2025",
    companyId: "pdd",
    companyName: "拼多多",
    companyNameEn: "PDD Holdings",
    ticker: "PDD",
    category: "互联网公司",
    iconUrl: "/company-icons/pdd.png",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/pdd-fy2025.json",
    status: "published",
  },
  {
    id: "jd-fy2025",
    companyId: "jd",
    companyName: "京东集团",
    companyNameEn: "JD.com",
    ticker: "9618.HK",
    category: "互联网公司",
    iconUrl: "https://www.jd.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/9618-hk-fy2025.json",
    status: "published",
  },
  {
    id: "baidu-fy2025",
    companyId: "baidu",
    companyName: "百度集团",
    companyNameEn: "Baidu",
    ticker: "BIDU",
    category: "互联网公司",
    iconUrl: "https://www.baidu.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/bidu-fy2025.json",
    status: "published",
  },
  {
    id: "alibaba-fy2025",
    companyId: "alibaba",
    companyName: "阿里巴巴集团",
    companyNameEn: "Alibaba Group",
    ticker: "9988.HK",
    category: "互联网公司",
    iconUrl: "https://www.alibaba.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY（截至3月31日）",
    publishedAt: "2026-08-22",
    endpoint: "/data/9988-hk-fy2025-2025-03-31.json",
    status: "published",
  },
  {
    id: "tencent-fy2025",
    companyId: "tencent",
    companyName: "腾讯控股",
    companyNameEn: "Tencent Holdings",
    ticker: "0700.HK",
    category: "互联网公司",
    iconUrl: "https://www.tencent.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/0700-hk-fy2025.json",
    status: "published",
  },
  {
    id: "didi-fy2025",
    companyId: "didi",
    companyName: "滴滴出行",
    companyNameEn: "DiDi Global",
    ticker: "DIDIY",
    category: "互联网公司",
    iconUrl: "https://website.didiglobal.com/DDlogo.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/didiy-fy2025.json",
    status: "published",
  },
  {
    id: "kuaishou-fy2025",
    companyId: "kuaishou",
    companyName: "快手科技",
    companyNameEn: "Kuaishou",
    ticker: "01024.HK",
    category: "互联网公司",
    iconUrl: "https://www.kuaishou.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/01024-hk-fy2025.json",
    status: "published",
  },
  {
    id: "meituan-fy2025",
    companyId: "meituan",
    companyName: "美团",
    companyNameEn: "Meituan",
    ticker: "03690.HK",
    category: "互联网公司",
    iconUrl: "https://www.meituan.com/favicon.ico",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/03690-hk-fy2025.json",
    status: "published",
  },
  {
    id: "netease-fy2025",
    companyId: "netease",
    companyName: "网易",
    companyNameEn: "NetEase, Inc.",
    ticker: "9999.HK",
    category: "互联网公司",
    iconUrl: "/company-icons/netease.svg",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-22",
    endpoint: "/data/9999-hk-fy2025.json",
    status: "published",
  },
  {
    id: "meta-2026-q1",
    companyId: "meta",
    companyName: "Meta Platforms",
    companyNameEn: "Meta Platforms, Inc.",
    ticker: "META",
    category: "AI公司",
    iconUrl: "/company-icons/meta.svg",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-19",
    endpoint: "/data/meta-2026q1.json",
    status: "published",
  },
  {
    id: "alphabet-2026-q2",
    companyId: "alphabet",
    companyName: "谷歌母公司 Alphabet",
    companyNameEn: "Alphabet Inc.",
    ticker: "GOOGL",
    category: "AI公司",
    iconUrl: "/company-icons/google.svg",
    fiscalYear: 2026,
    quarter: "Q2",
    periodLabel: "2026 Q2",
    publishedAt: "2026-08-19",
    endpoint: "/data/googl-2026q2.json",
    status: "published",
  },
  {
    id: "alphabet-2026-q1",
    companyId: "alphabet",
    companyName: "谷歌母公司 Alphabet",
    companyNameEn: "Alphabet Inc.",
    ticker: "GOOGL",
    category: "AI公司",
    iconUrl: "/company-icons/google.svg",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-19",
    endpoint: "/data/googl-2026q1.json",
    status: "published",
  },
  {
    id: "tripcom-2026-q1",
    companyId: "tripcom",
    companyName: "携程集团",
    companyNameEn: "Trip.com Group",
    ticker: "9961.HK",
    category: "互联网公司",
    iconUrl: "/company-icons/tripcom.svg",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-13",
    endpoint: "/data/9961-hk-2026q1.json",
    status: "published",
  },
  {
    id: "minimax-fy2025",
    companyId: "minimax",
    companyName: "稀宇科技",
    companyNameEn: "MiniMax",
    ticker: "0100.HK",
    category: "AI公司",
    iconUrl: "/company-icons/minimax.png",
    fiscalYear: 2025,
    quarter: "FY",
    periodLabel: "2025 FY",
    publishedAt: "2026-08-11",
    endpoint: "/data/minimax-fy2025.json",
    status: "published",
  },
  {
    id: "pdd-2026-q1",
    companyId: "pdd",
    companyName: "拼多多",
    companyNameEn: "PDD Holdings",
    ticker: "PDD",
    category: "互联网公司",
    iconUrl: "/company-icons/pdd.png",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-10",
    endpoint: "/data/pdd-2026q1.json",
    status: "published",
  },
  {
    id: "jd-2026-q1",
    companyId: "jd",
    companyName: "京东集团",
    companyNameEn: "JD.com",
    ticker: "9618.HK",
    category: "互联网公司",
    iconUrl: "https://www.jd.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-03",
    endpoint: "/data/9618-hk-2026q1.json",
    status: "published",
  },
  {
    id: "baidu-2026-q1",
    companyId: "baidu",
    companyName: "百度集团",
    companyNameEn: "Baidu",
    ticker: "BIDU",
    category: "互联网公司",
    iconUrl: "https://www.baidu.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-07-31",
    endpoint: "/data/bidu-2026q1.json",
    status: "published",
  },
  {
    id: "alibaba-2026-fy",
    companyId: "alibaba",
    companyName: "阿里巴巴集团",
    companyNameEn: "Alibaba Group",
    ticker: "9988.HK",
    category: "互联网公司",
    iconUrl: "https://www.alibaba.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "FY",
    periodLabel: "2026 FY",
    publishedAt: "2026-07-31",
    endpoint: "/data/alibaba-2026-fy.json",
    status: "published",
  },
  {
    id: "tencent-2026-q2",
    companyId: "tencent",
    companyName: "腾讯控股",
    companyNameEn: "Tencent Holdings",
    ticker: "0700.HK",
    category: "互联网公司",
    iconUrl: "https://www.tencent.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q2",
    periodLabel: "2026 Q2",
    publishedAt: "2026-08-12",
    endpoint: "/data/tencent-2026-q2.json",
    status: "published",
  },
  {
    id: "tencent-2026-q1",
    companyId: "tencent",
    companyName: "腾讯控股",
    companyNameEn: "Tencent Holdings",
    ticker: "0700.HK",
    category: "互联网公司",
    iconUrl: "https://www.tencent.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-07-30",
    endpoint: "/data/tencent-2026-q1.json",
    status: "published",
  },
  {
    id: "didi-2026-q2",
    companyId: "didi",
    companyName: "滴滴出行",
    companyNameEn: "DiDi Global",
    ticker: "DIDIY",
    category: "互联网公司",
    iconUrl: "https://website.didiglobal.com/DDlogo.ico",
    fiscalYear: 2026,
    quarter: "Q2",
    periodLabel: "2026 Q2",
    publishedAt: "2026-08-18",
    endpoint: "/data/didiy-2026q2.json",
    status: "published",
  },
  {
    id: "didi-2026-q1",
    companyId: "didi",
    companyName: "滴滴出行",
    companyNameEn: "DiDi Global",
    ticker: "DIDIY",
    category: "互联网公司",
    iconUrl: "https://website.didiglobal.com/DDlogo.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-07-30",
    endpoint: "/data/didi-2026-q1.json",
    status: "published",
  },
  {
    id: "kuaishou-2026-q1",
    companyId: "kuaishou",
    companyName: "快手科技",
    companyNameEn: "Kuaishou",
    ticker: "01024.HK",
    category: "互联网公司",
    iconUrl: "https://www.kuaishou.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-07-27",
    endpoint: "/data/kuaishou-2026-q1.json",
    status: "published",
  },
  {
    id: "meituan-2026-q1",
    companyId: "meituan",
    companyName: "美团",
    companyNameEn: "Meituan",
    ticker: "03690.HK",
    category: "互联网公司",
    iconUrl: "https://www.meituan.com/favicon.ico",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-06-01",
    endpoint:
      process.env.NEXT_PUBLIC_FINANCIAL_DATA_URL ?? DEFAULT_ENDPOINT,
    status: "published",
  },
  {
    id: "netease-2026-q1",
    companyId: "netease",
    companyName: "网易",
    companyNameEn: "NetEase, Inc.",
    ticker: "9999.HK",
    category: "互联网公司",
    iconUrl: "/company-icons/netease.svg",
    fiscalYear: 2026,
    quarter: "Q1",
    periodLabel: "2026 Q1",
    publishedAt: "2026-08-21",
    endpoint: "/data/9999-hk-2026q1.json",
    status: "published",
  },
];

export const PUBLISHED_REPORTS = REPORT_CATALOG.filter(
  (report) => report.status === "published",
).sort(
  (a, b) =>
    new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime(),
);

export const COMPANY_OPTIONS = Array.from(
  new Map(
    PUBLISHED_REPORTS.map((report) => [
      report.companyId,
      {
        id: report.companyId,
        name: report.companyName,
        nameEn: report.companyNameEn,
        ticker: report.ticker,
        category: report.category,
        iconUrl: report.iconUrl,
      },
    ]),
  ).values(),
);

export function reportsForCompany(companyId: string) {
  return PUBLISHED_REPORTS.filter((report) => report.companyId === companyId);
}

export function companiesForCategory(category: ResearchCategory) {
  return COMPANY_OPTIONS.filter((company) => company.category === category);
}

export function getDefaultReport() {
  return PUBLISHED_REPORTS[0];
}
